
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parsers.cup;

/** CUP generated interface containing symbol constants. */
public interface ExpressionParserSym {
  /* terminals */
  public static final int ELSE = 19;
  public static final int PLUS = 5;
  public static final int RBRACE = 13;
  public static final int RPAREN = 9;
  public static final int INT = 10;
  public static final int SEMI = 15;
  public static final int STAR = 6;
  public static final int RETURN = 17;
  public static final int IDENTIFIER = 4;
  public static final int POW = 7;
  public static final int IF = 18;
  public static final int LPAREN = 8;
  public static final int LBRACE = 12;
  public static final int BOOLEAN = 3;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int BOOL = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "BOOLEAN",
  "IDENTIFIER",
  "PLUS",
  "STAR",
  "POW",
  "LPAREN",
  "RPAREN",
  "INT",
  "BOOL",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "EQ",
  "RETURN",
  "IF",
  "ELSE"
  };

  /* non terminals */
  static final int Type = 2;
  static final int NonemptyParamList = 8;
  static final int FuncDecl = 1;
  static final int ParamList = 7;
  static final int FunctionCall = 9;
  static final int NonemptyArgList = 5;
  static final int ArgList = 4;
  static final int Exp = 6;
  static final int Statements = 11;
  static final int Statement = 10;
  static final int CompUnit = 0;
  static final int Arg = 3;
}

